version: '3.3'

services:
  postgres:
    container_name: postgres_peuan_container
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - peuan

  pgadmin:
    container_name: pgadmin_peuan_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - peuan

  redis:
    container_name: redis_peuan_container
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - peuan

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch_peuan_container
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - peuan
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana_peuan_container
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - kibana:/var/lib/kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - peuan

networks:
  peuan:

volumes:
  redis:
  postgres:
  pgadmin:
  elasticsearch:
  kibana:
