version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    working_dir: /opt/app
    command: npm run start:debug
    volumes:
      - ./:/opt/app
      # - /opt/app/node_modules/
    ports:
      - '5000:5000'
    networks:
      - note
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres_note_container
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - note

  pgadmin:
    container_name: pgadmin_note_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - note

  redis:
    container_name: redis_note_container
    image: redis:6.0-buster
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    hostname: ${REDIS_HOST}
    networks:
      - note

networks:
  note:

volumes:
  redis:
  postgres:
  pgadmin:
